### ISSUE TITLE
min (resp. max) calculation wrong if station has no negative (resp. positive) temperature

### ISSUE THREAD

**Issue by setop** [benhoyt/go-1brc#1]
https://github.com/benhoyt/go-1brc/blob/fafba3256ea28631f6b3739f6d3b711a91199861/1brc.awk#L6

In this statement, if station has never been encountered,`mins[$1]` is initialized to 0. If station has no negative value, min stays at zero, producing wrong result. Same for maxs.

```bash
$ wget https://github.com/benhoyt/go-1brc/raw/master/1brc.awk

$ cat << EOF > m.txt 
A;1
A;4
A;2
EOF

$ gawk -F\; -f 1brc.awk m.txt 
{A=0.0/2.3/4.0}  # wrong, min is 1
```

Any [valid solution](https://github.com/gunnarmorling/1brc/discussions/171#discussioncomment-8033057) must test if a station already has an entry or not.

BTW, nice post. I enjoyed reading about optimizing go code using profiling.

**Comment by benhoyt** [comment]
Yeah, good point. Would you like to propose a PR that does `if (counts[$1]) ...` or similar?

**Comment by shadowrun96** [comment]
Great! why don't you show us your own fix and the benchmark results? 
But yeah, I had a passing thought that you need to check against a range and not a single value, but I was too tired by the end of it, and moved on to finish the rest of the AWK book instead :-)
