### ISSUE TITLE
R8: Potential data loss when breaking loop at seekOffset > size

### ISSUE THREAD

**Issue by Shaheen-AlQaraghuli** [benhoyt/go-1brc#3]
I think breaking the loop in the code below might result in missing data at the end of the file
https://github.com/benhoyt/go-1brc/blob/e9fe448f8b3cce4fa82c3c8af7ae2e901ef04903/r8.go#L144C6-L144C23

Wouldn't something like the below be better?
```counter := 1
for offset < size {
	if numParts == counter {
		parts = append(parts, part{offset, size-offset})
		return parts, nil
	}
	seekOffset := max(offset+splitSize-maxLineLength, 0)
	if seekOffset > size {
		seekOffset = size - (size - offset)
	}
	//rest of the logic 
	counter++
}

**Comment by benhoyt** [comment]
I *think* the end of the file will be covered by the previous append to parts. However, I haven't thought through it too carefully -- if you can add a test case that fails (maybe `TestMissingEnd` in an `r8_test.go`) with a simple fix, I'd be happy to include look at it.

**Comment by Shaheen-AlQaraghuli** [comment]
@benhoyt 
Created a [PR](https://github.com/benhoyt/go-1brc/pull/5) which includes a test for r8 and a suggested fix.

**Comment by benhoyt** [comment]
Merged your PR, thanks!
